---
service:
  client: 10.0.0.200
  port: 12345
functions:
  changettl:
    type: switch
    file: $CHIMA_ROOT/measurements/large/functions/changettl.p4
    control: changettl_control
    next: toupper
  toupper:
    type: container
    latency: 5000
    jitter: 5000
    file: $CHIMA_ROOT/measurements/large/toupper.yaml
    next: changettl2
  changettl2:
    type: switch
    file: $CHIMA_ROOT/measurements/large/functions/changettl.p4
    control: changettl_control
    next: replace
  replace:
    type: container
    file: $CHIMA_ROOT/measurements/large/replace.yaml
    next: changettl3
  changettl3:
    type: switch
    file: $CHIMA_ROOT/measurements/large/functions/changettl.p4
    control: changettl_control
    next: widen
  widen:
    type: container
    file: $CHIMA_ROOT/measurements/large/widen.yaml
    next: changettl4
  changettl4:
    type: switch
    file: $CHIMA_ROOT/measurements/large/functions/changettl.p4
    control: changettl_control
    next: echo
  echo:
    type: container
    file: $CHIMA_ROOT/measurements/large/echo.yaml